HW9RegistrationTest/blog/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "profile", to: "authors#edit", as: "profile"

  resources :posts do
    resources :comments do
      member do
        post :publish
      end
      resources :votes
      post 'dislikes' => 'votes#dislike'
    end
    get "search", on: :collection
  end
  post 'posts/:id', to: 'posts#show'
  get 'search', to: 'posts#search'

  resources :authors
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

HW9RegistrationTest/blog/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :comments, -> { order "updated_at DESC" }, dependent: :destroy
  has_rich_text :content
  validates :title, :content, presence: true
  validates :content, length: { maximum: 1000,
    too_long: "%{count} characters is the maximum allowed" }
  validates :title, length: { maximum: 40,
    too_long: "%{count} characters is the maximum allowed" }
  validates :image, url: {allow_blank: true}
end

HW9RegistrationTest/blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_cookies
  before_action :check_current_author, only: [:new, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:author)
    @pagy, @posts = pagy(Post.all.order(created_at: :desc), items: 8)
  end

  def search
    @posts = Post.where('content ILIKE ? OR title ILIKE ?', "%#{params[:query]}%", "%#{params[:query]}%")
    @pagy, @records = pagy(@posts, items: 8)
    render :index
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post.increment!(:views_count)
    @comment_status = params[:comments_status].to_s.downcase
    @comments = if @comment_status == 'unpublished'
                  @post.comments.unpublished
                else
                  @post.comments.published
                end
    @comments = @post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

   # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.author_id = current_author.id
    @post.title = @post.author.full_name
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_cookies
    unless current_author
      cookies[:views] = cookies[:views] ? cookies[:views].to_i + 1 : 1
    end
  end

  def check_current_author
    unless current_author
      redirect_to home_url
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :image, :author_id)
  end
end

HW9RegistrationTest/blog/app/helpers/posts_helper.rb
module PostsHelper
end

HW9RegistrationTest/blog/app/views/posts/_form.html.erb
<div class="container">

<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul class="list-unstyled">
        <% post.errors.each do |error| %>
          <li class="alert alert-danger"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field py-2">
    <%= form.label :name, class: "pb-2" %>
    <%= form.select(:author_id, Author.all.collect.each {|a| [ a.full_name, a.id ] }, {}, {:class => "select_author"}) %>
  </div>

 <div class="field py-2">
    <%= form.label :title, class: "pb-2" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field py-2">

    <%= form.label :content, class: "pb-2" %>
    <%= form.rich_text_area :content, class: "form-control" %>
  </div>

  <div class="field py-2">
    <%= form.label :image, class: "img-fluid" %>
    <%= form.text_field :image, class: "form-control" %>
  </div>

  <div class="actions py-2 d-flex justify-content-center d-flex align-items-center">
    <%= form.submit(class: "btn btn-success btn-lg") %>
  </div>
<% end %>
</div>

HW9RegistrationTest/blog/app/views/posts/_pagination.html.erb
<%== pagy_bootstrap_nav(@pagy) %>

HW9RegistrationTest/blog/app/views/posts/edit.html.erb
<div class="container">
  <h1 class="mt-3 text-center">Editing Post</h1>

  <%= render 'form', post: @post %>

  <div class="d-flex justify-content-center d-flex align-items-center">
    <%= link_to 'Show', @post, class: "btn btn-secondary my-3 btn-lg" %> &nbsp;|&nbsp;
    <%= link_to 'Back', posts_path, class: "btn btn-secondary my-3 btn-lg" %>
  </div>

</div>

HW9RegistrationTest/blog/app/views/posts/index.html.erb
 <div class="container">
   <p id="notice" class="text-center my-3 fs-3 text-secondary" id="notice"><%= notice %></p>

     <h1 class="container text-center p-3 mb-2 bg-light text-dark">Posts</h1>

      <% if @posts.empty? %>
        <div class="text-center">
          <h2>The posts list is empty at the moment...</h2>
        </div>
     <hr>
      <% else %>

     <div class="table-responsive">
      <table class="table table-striped table-hover table-sm align-middle">
        <thead class="container text-center">
          <tr>
            <th>Author</th>
            <th>Title</th>
            <th>Content</th>
            <th>Image</th>
            <th>Views Count</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody class="container">

          <% @posts.each do |post| %>
            <tr class="container text-center">
              <td><%= image_tag post.author.avatar.variant(resize_to_limit: [45, 45]) if post.author.avatar.present? %><%= post.author.full_name %></td>
              <td><%= post.title %></td>
              <td class="text-start"><%= post.content %></td>
              <td><%= image_tag(post.image, width: '200', class: "mx-auto d-block") %></td>
              <td><%= post.views_count %></td>
              <td>
                <div class="d-flex p-2 bd-highlight mb-3 align-items-center">
                <%= link_to 'Show', post, class: "btn btn-success" %> |
                <% if post.author == current_author %>
                  <%= link_to 'Edit', edit_post_path(post), class: "btn btn-secondary" %> |
                  <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure you want to delete the post?' }, class: "btn btn-danger" %>
                <% else %>
                    <div class="btn-group"
                       tabindex="0"
                       title="Only the author of the post can edit and delete">
                    <%= link_to 'Edit', home_path, class: "btn btn-secondary disabled" %>
                    <%= link_to 'Delete', home_path, class: "btn btn-dark disabled" %><br/>
                    </div>
                <% end %>
                <% end %>
                </div>
              </td>
            </tr>
         </tbody>
    </table>
  </div>
  <% end %>
 </div>

  <div class="d-flex justify-content-center d-flex align-items-center">
    <%= link_to 'New Post', new_post_path, class: "btn btn-success btn-lg" if current_author %>
  </div>
 <hr>
  <div class="d-flex justify-content-center d-flex align-items-center">
    <%= render 'posts/pagination', locals: { pagy: @pagy } %>
  </div>
 <%= render 'layouts/sign_in_modal' %>

HW9RegistrationTest/blog/app/views/posts/new.html.erb
<div class="container">

<h1 class="mt-3 text-center">New Post</h1>

  <div class="container">
    <%= render 'form', post: @post %>
  </div>

<div class="d-flex justify-content-center d-flex align-items-center">
  <%= link_to 'Back', posts_path, class: "btn btn-secondary my-3 btn-lg" %>
</div>

  <hr>

</div>

HW9RegistrationTest/blog/app/views/posts/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p class="text-center mb-3">
  <%= image_tag @post.author.avatar.variant(resize_to_limit: [100, 100]) if @post.author.avatar.present? %>
  <strong>Author:</strong>
  <%= @post.author.full_name %>
</p>

<p class="text-center mb-3">
  <strong>Author ID:</strong>
  <%= @post.author_id %>
</p>

<p class="text-center mb-3">
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p class="text-center mb-3">
  <%= image_tag(@post.image, width: "500", alt: "Post image", class: "img-fluid py-4") if @post.image.present? %>
</p>

<p class="text-center mb-3">
  <strong>Content:</strong>
  <%= @post.content %>
</p>
  <hr>
  <div class="d-flex justify-content-center d-flex align-items-center">
    <h5>This post has been updated <%= distance_of_time_in_words(Time.now, @post.updated_at) %> ago.</h5>
  </div>

  <div class="d-flex justify-content-center d-flex align-items-center">
    <strong>Views:</strong>&nbsp;
    <%= @post.views_count %>
  </div>

  <div class="d-flex justify-content-center d-flex align-items-center">
    <strong> Total: </strong>&nbsp;
   <%= @post.comments_count || 0 %> <%= @post.comments_count != 1 ? ' comments' : ' comment' %>
  </div>
  <hr>
  <div class="d-flex justify-content-center d-flex align-items-center">
    <% if @post.author == current_author %>
      <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-secondary btn-lg" %>
    <% else %>
      <div class="d-inline-block"
           tabindex="0"
           title="You are not the author of the post">
        <%= link_to 'Edit', edit_post_path(@post),
                    class: "btn btn-secondary disabled",
                    id: "btn-disabled" %>
      </div>
    <% end %>
      &nbsp;|&nbsp;
    <%= link_to 'Back', posts_path, class: "btn btn-secondary btn-lg" %>
  </div>
 <hr>

  <div class="comments my-5">
    <h5 class="py-5 text-center">Comments</h5>
    <hr>

    <div class="text-right pb-4 ">
      <%= form_with(model: @comment, scope: :status, url: @post) do |form| %>

        <div class="field btn btn-primary comment-statuses">
          <%= form.select :status, Comment.statuses { |a| a }, selected: params[:status] == {"status"=>"0"} ? 0 : 1, class: "btn btn-primary" %>
        </div>
        <div class="actions">
          <%= form.submit 'Show comments', class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  <hr>
    <div class="new-comment" id="new-comment">
      <%= nested_comments @post.comments.arrange %>
    </div>
  <hr>
  </div>
  <h5 class="mt-5"> Add a new comment:</h5>
  <% if current_author %>
    <div id="comment-reply-root">
      <%= render 'comments/form', comment_id: nil %>
    </div>
    <hr>
  <% else %>
    <p class="py-4">Please register in the system</p>
  <% end %>
</div>