HW9RegistrationTest/blog/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "profile", to: "authors#edit", as: "profile"

  resources :posts do
    resources :comments do
      member do
        post :publish
      end
      resources :votes
      post 'dislikes' => 'votes#dislike'
    end
    get "search", on: :collection
  end
  post 'posts/:id', to: 'posts#show'
  get 'search', to: 'posts#search'

  resources :authors
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

HW9RegistrationTest/blog/app/models/comment.rb
class Comment < ApplicationRecord
  has_ancestry
  has_many :author_comment_votes, dependent: :destroy
  belongs_to :post, counter_cache: true
  belongs_to :author
  validates :body, presence: true
  validates :body, presence: true
  enum status: %i[unpublished published]
  scope :published, -> { where(status: 1) }
  scope :unpublished, -> { where(status: 0) }
 end

HW9RegistrationTest/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :edit, :update, :destroy, :publish, :new]
  before_action :set_comment, only: [:update, :destroy, :edit, :publish, :destroy]
  before_action :set_cookies

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(comments_params)
    @comment.author_id = current_author.id
    if @comment.ancestors.count > 5
      redirect_to @post, notice: 'Stop flooding, comments nesting exceeded'
    else
      if @comment.save
        render 'comments/create'
        # redirect_to @post, notice: "Post was successfully created."
      else
        parent_id = @comment.parent ? @comment.parent.id : nil
        redirect_to @post, flash: { comment_error: @comment.errors.full_messages.join(', '), comment_id: parent_id }
      end
    end
  end

  def edit
  end

  def update
    @comment.edited_at = Time.now
    @comment.update(comments_params)
    redirect_to @post, notice: "Comment was edited."
  end

  def publish
    @comment.update(comments_params)
    redirect_to @post, notice: "Comment was published!"
  end

  def destroy
    if @comment.destroy
      render 'destroy'
    else
      redirect_to @post
    end
    # redirect_to @post, notice: "Comment was successfully deleted."
  end

  private

  def set_cookies
    unless current_author
      cookies[:views] = cookies[:views] ? cookies[:views].to_i + 1 : 1
    end
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comments_params
    params.require(:comment).permit(:author_id, :body, :status, :parent_id)
  end
end

HW9RegistrationTest/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

HW9RegistrationTest/blog/app/views/comments/_comment.html.erb
<% unpublished_comment = comment.status == "unpublished" %>
<% diff_edit_comment_time = Time.now - comment.created_at %>

<div id="comment-<%= comment.id %>" class="comment mb-3">
  <div class="comment-header d-flex justify-content-between">
    <strong class="mr-3">
      <%= image_tag comment.author.avatar.variant(resize_to_limit: [40, 40]),
                    class: "mr-3" if comment.author.avatar.present? %>
      <%= comment.author.first_name %> <%= comment.author.last_name %>
    </strong>

    <div class="votes"
         title="👍<%= comment.author_comment_votes.where(vote_value: 1).count %> | 👎<%= comment.author_comment_votes.where(vote_value: -1).count %> | Total voted:<%= comment.author_comment_votes.count %>">

      <strong>Comment rating: <%= comment.author_comment_votes.map(&:vote_value).sum %></strong>
      <% unless current_author == comment.author %>
        <div class="vote-button mb-3 text-right">
          <% if current_author %>
            <% if comment.author_comment_votes.find { |vote| vote.author_id == current_author.id } %>
              <p>You have already voted</p>
            <% else %>
              <%= link_to '👍', post_comment_votes_path(@post, comment),
                          remote: true,
                          method: :post,
                          class: 'btn btn-dark btn-sm fs-4' %>
              <%= link_to '👎', post_comment_dislikes_path(@post, comment),
                          remote: true,
                          method: :post,
                          class: 'btn btn-dark btn-sm fs-4' %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="d-block p-3">
    <p><%= comment.body %></p>
  </div>

  <p class="text-right fst-italic">Comment created
    <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago
  </p>

  <% if unpublished_comment %>
    <p class="alert-danger">Comment <%= comment.status %></p>
  <% end %>
  <% if comment.edited_at? %>
    <p class="alert-danger">Comment edited <%= distance_of_time_in_words(comment.updated_at, Time.now) %> ago</p>
  <% end %>

  <div class="d-flex justify-content-between align-items-center mr-1">
    <% unless current_author == comment.author %>
      <div id="comment-reply-<%= comment.id %>" class="comment-reply">
        <%= link_to 'Reply', new_post_comment_path(@post,
                                                   comment_id: comment.id),
                    remote: true,
                    class: "btn btn-primary mb-4" if current_author %>
      </div>
    <% end %>
    <% if comment.author == current_author %>
      <div class="d-block text-right mb-3 btn-group ml-auto">
        <% if unpublished_comment %>
          <%= link_to 'Publish', publish_post_comment_path(@post, comment, comment: { status: :published }),
                      method: :post,
                      class: "btn btn-success" %>
        <% end %>

        <% if diff_edit_comment_time >= 1.hour %>
          <div class="d-inline-block" tabindex="0" title="No editing possible - more than an hour has passed since the comment was created">
            <%= link_to 'Edit', home_path, class: "btn btn-secondary disabled" %>
          </div>
        <% else %>
          <%= link_to 'Edit', edit_post_comment_path(comment.post, comment),
                      class: "btn btn-secondary" %>
        <% end %>
        <%= link_to 'Delete', post_comment_path(@post, comment),
                    remote: true,
                    method: :delete,
                    data: { confirm: 'Are you sure you want to delete the comment?' },
                    class: "btn btn-danger" %>
      </div>
    <% else %>
    <% end %>
  </div>
  <% if flash[:comment_error].present? && flash[:comment_id].to_i == comment.id %>
    <div id="error_explanation">
      <p class="alert alert-danger"><%= flash[:comment_error] %></p>
    </div>
  <% end %>
</div>

HW9RegistrationTest/blog/app/views/comments/_form.html.erb
<%= form_with model: [@post, @post.comments.build], local: false, class: "comment-form" do |form| %>

  <div class="field py-2">
    <%= form.text_area :body, class: "form-control", placeholder: "Enter your comment here..." %>
  </div>

  <%= form.hidden_field :parent_id, value: params[:comment_id] if params[:comment_id].present? %>

  <div class="btn btn-primary">
    <%= form.select(:status, [['Unpublished', :unpublished], ['Published', :published]], class: "btn btn-success") %>
  </div>

  <div class="actions py-2">
    <%= form.submit(class: "btn btn-success") %>
  </div>
<% end %>

HW9RegistrationTest/blog/app/views/comments/create.js.erb
$('.new-comment').replaceWith("<div class='new-comment'><%= j nested_comments @post.comments.arrange%></div>")
$('#comment-reply-root .comment-form')[0].reset();

HW9RegistrationTest/blog/app/views/comments/destroy.js.erb
$('#comment-<%= @comment.id %>').hide(400)

HW9RegistrationTest/blog/app/views/comments/edit.html.erb
<%= link_to 'Back', posts_path, class: "btn btn-secondary my-3" %>
<h1 class="mt-3 text-center">Editing comment</h1>

<%= form_with model: [@post, @comment] do |form| %>

  <div class="field py-2">
    <%= form.label "Comment", class: "pb-2" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="actions py-2">
    <%= form.submit(class: "btn btn-success") %>
  </div>
<% end %>

HW9RegistrationTest/blog/app/views/comments/new.js.erb
$('.comment-reply').show()
$('.comment-form').hide()
$('#comment-reply-<%= params[:comment_id] %>').parent().after('<%= j render('form') %>').slideUp(400)
$('#comment-reply-<%= params[:comment_id] %>').hide()
$('#comment-reply-root .comment-form').show()