HW9RegistrationTest/blog/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get "profile", to: "authors#edit", as: "profile"

  resources :posts do
    resources :comments do
      member do
        post :publish
      end
      resources :votes
      post 'dislikes' => 'votes#dislike'
    end
    get "search", on: :collection
  end
  post 'posts/:id', to: 'posts#show'
  get 'search', to: 'posts#search'

  resources :authors
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

HW9RegistrationTest/blog/app/views/layouts/_sign_in_modal.html.erb
<div class="modal fade" id="logInModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Please log in</h5>
      </div>
      <div class="modal-body">
        <%= render 'sessions/form' %>
      </div>
      <div class="text-center border-top border-dark my-3 pt-3">
        <%= link_to "Register", signup_path, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

HW9RegistrationTest/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', async: true %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom shadow-sm px-4">
    <h2 class="px-2 m-0 text-uppercase"><%= link_to "Blog", home_path, class: "text-decoration-none text-dark" %></h2>
    <% if current_author %>
      <div class="ml-3 d-flex align-items-center text-nowrap">
        <p class="m-0 fs-5">Logged in as <%= current_author.full_name %></p>
        <%= image_tag current_author.avatar.variant(resize_to_limit: [50, 50]), class: "img-fluid px-3" if current_author.avatar.present? %>
      </div>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="p-2">
          <%= form_with url: search_posts_path, method: :get, local: true, class: "input-group" do |form| %>
            <%= form.text_field :query, id: :query, class: "form-control", placeholder: "Search" %>
            <div class="input-group-append">
              <%= form.submit "Find", class: "btn btn-success" %>
            </div>
          <% end %>
        </li>
        <% if current_author %>
          <li class="p-2">
            <%= link_to "Edit profile", profile_path, class: "btn btn-outline-success" %>
          </li>
          <li class="p-2">
            <%= link_to "Log Out", logout_path, class: "btn btn-danger" %>
          </li>
        <% else %>
          <li class="p-2">
            <%= link_to "Register", signup_path, id: "register", class: "btn btn-success" %>
          </li>
          <li class="p-2">
            <%= link_to "Log In", login_path, class: "btn btn-success" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <div class="container mb-5">
    <%= yield %>
  </div>
  <% if cookies[:views].to_i == 5 %>
    <script type="text/javascript">
        $('#logInModal').modal('show')
    </script>
    <% cookies.delete(:views) %>
  <% end %>
  <%= render 'layouts/sign_in_modal' %>
  <span id="back">
    <a href="">
      <%= image_tag asset_path('arrow.jpg'), data: {"turbolinks"=>false}, class: "arrow" %>
    </a>
  </span>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>